{
    "Service": "/MDKApp/Services/com_sap_edm_sampleservice_v4.service",
    "DefiningRequests": [{
            "Name": "Customers",
            "Query": "Customers"
        },
        {
            "Name": "Products",
            "Query": "Products"
        },
        {
            "Name": "PurchaseOrderHeaders",
            "Query": "PurchaseOrderHeaders"
        },
        {
            "Name": "PurchaseOrderItems",
            "Query": "PurchaseOrderItems"
        },
        {
            "Name": "SalesOrderHeaders",
            "Query": "SalesOrderHeaders"
        },
        {
            "Name": "SalesOrderItems",
            "Query": "SalesOrderItems"
        }
    ],
    "_Type": "Action.Type.OfflineOData.Download",
    "ActionResult": {
        "_Name": "sync"
    },
    "OnFailure": "/MDKApp/Actions/com_sap_edm_sampleservice_v4/Service/SyncFailureMessage.action",
    "OnSuccess": "/MDKApp/Rules/com_sap_edm_sampleservice_v4/ErrorArchive_CheckForSyncError.js"
}