{
    "Service": "/MDKApp/Services/com_sap_edm_sampleservice_v4.service",
    "DefiningRequests": [{
            "Name": "Customers",
            "Query": "Customers"
        },
        {
            "Name": "Products",
            "Query": "Products"
        },
        {
            "Name": "PurchaseOrderHeaders",
            "Query": "PurchaseOrderHeaders"
        },
        {
            "Name": "PurchaseOrderItems",
            "Query": "PurchaseOrderItems"
        },
        {
            "Name": "SalesOrderHeaders",
            "Query": "SalesOrderHeaders"
        },
        {
            "Name": "SalesOrderItems",
            "Query": "SalesOrderItems"
        }
    ],
    "_Type": "Action.Type.ODataService.Initialize",
    "ShowActivityIndicator": true,
    "ActivityIndicatorText": "Downloading...",
    "ActionResult": {
        "_Name": "init"
    },
    "OnFailure": "/MDKApp/Actions/com_sap_edm_sampleservice_v4/Service/InitializeOfflineFailureMessage.action"
}